image:
  file: .gitpod/gitpod.Dockerfile

tasks:
  - name: Bazel
    before: "./.gitpod/gitpod-init.sh"
    init: |
      bazel build //...

vscode:
  extensions:
    - BazelBuild.vscode-bazel@0.5.0
    - Ionide.Ionide-fsharp@5.10.2
    - muhammad-sammy.csharp@1.24.0

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
